wm_enc_config:
  image_size: 256
  message_length: 64
  in_channels: 3
  tp_channels: 32
  mask_channel: 0
  channels: 64
  norm_type: group
wm_dec_config:
  image_size: 256
  message_length: 64
  in_channels: 3
  tp_channels: 32
  mask_channel: 1
  channels: 128
  norm_type: group
